version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./app/input_files:/code/input_files
      - ./app/output_files:/code/output_files
    depends_on:
      - ffmpeg

  ffmpeg:
    image: jrottenberg/ffmpeg:latest
    volumes:
      - ./app/input_files:/input
      - ./app/output_files:/output
    command: ["tail", "-f", "/dev/null"]