version: '3.8'

services:
  # 1. API (Backend, Puerto 80)
  api:
    build: .
    container_name: practice2-api-container
    ports:
      - "80:80"
    volumes:
      - ./app:/code/app
      - ./input_files:/code/app/input_files
      - ./output_files:/code/app/output_files
    working_dir: /code 
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 80
    
  # 2. GUI (Frontend Streamlit, Puerto 8000)
  gui:
    build: .
    container_name: practice2-gui-container
    ports:
      # GUI accesible en http://localhost:8000
      - "8000:8501" 
    volumes:
      - ./gui.py:/code/app/gui.py
      - ./input_files:/code/app/input_files
      - ./output_files:/code/app/output_files
    environment:
      # La GUI llama a la API por el nombre del servicio 'api'
      - API_HOST=http://api:80
    command: streamlit run /code/app/gui.py --server.port 8501 --server.address 0.0.0.0
    depends_on:
      - api